FE-Ocean/MEETSIN

- client/src/components/chat/message/message.module.scss
- client/src/components/chat/messageInput/messageInput.module.scss
- client/src/components/modals/timerSetting/timerSetting.module.scss
- client/src/components/screen/screen.module.scss
- client/src/components/screen/window/screen_window.module.scss
- client/src/styles/_variables.scss
색상 변수 추가 및 적용하였습니다.
- 모노톤 색 변수 5개가 추가
(black(#ffffff)은 디폴트 값이라 추가하지 않음)
> design: 새로운 색상 변수 추가 및 적용

- client/src/app/page.tsx
- client/src/components/menu/menu.tsx
- client/src/components/modals/timerSetting/timerSetting.tsx
- client/src/components/screen/window/screenWindow.tsx
- client/src/components/timer/timer.module.scss
- client/src/components/timer/timer.tsx
- client/src/jotai/atom.ts
- client/src/store/store.ts
- client/src/utills/index.ts
- client/src/utils/index.ts
중복 폴더 통합 및 타이머 간격 조정하였습니다.
- utils 폴더 통합
- atom파일 jotai 폴더로 통합 및 확장자 ts로 변경
- 타이머 간격 조정
> fix: 중복 폴더 통합 및 타이머 간격 조정

- client/src/app/room/[roomId]/page.tsx
- client/src/components/screen/screen.tsx
- client/src/components/screen/window/screenWindow.tsx
- client/src/modules/fetchClient.ts
- server/src/auth/auth.controller.ts
- server/src/auth/auth.guard.ts
- server/src/auth/auth.module.ts
- server/src/auth/auth.service.ts
- server/src/auth/google.strategy.ts
- server/src/auth/jwt.strategy.ts
- server/src/auth/kakao.strategy.ts
- server/src/common/decorators/user.decorator.ts
- server/src/rooms/rooms.controller.ts
- server/src/rooms/rooms.service.ts
- server/src/schema/user.schema.ts
- server/src/types/request.type.ts
- server/src/users/users.repository.ts
- server/src/users/users.service.ts
> fix: 클라이언트 타입스크립트 에러 수정 및 서버 로그인 쿠키 maxAge 지정 

- client/src/socket.ts
- server/src/app.module.ts
- server/src/auth/auth.controller.ts
- server/src/phaser/phaser.gateway.ts
- server/src/rooms/rooms.gateway.ts
프로덕션 배포 관련 수정 
- 소켓 설정 변경
- CORS 관련 옵션 추가 및 정리
-  cookieOptions 설정
- 환경변수 `MODE` 값 변경에 따른 수정
> fix: 프로덕션 배포 관련 수정

- client/src/app/room/[roomId]/page.tsx
fix:  roomTitle 가져올 떄 필요한 (생략된)useGetRoomData 훅 추가
fix:  roomTitle 가져올 떄 필요한 (생략된)useGetRoomData 훅 추가
> release: 1.0.2 배포

- client/src/app/analysis.tsx
- client/src/app/layout.tsx
clarity 작동시키기 위해 코드 추가했습니다
- Analysis 컴포넌트 레이아웃에 추가
> feat: clarity 설정

- client/public/icons/zoom_in.svg
- client/public/icons/zoom_out.svg
- client/src/app/page.tsx
- client/src/app/room/[roomId]/page.tsx
- client/src/components/button/mapZoom/mapZoomButtons.module.scss
- client/src/components/button/mapZoom/mapZoomButtons.tsx
- client/src/components/common/userInfo/userMenu/userMenu.module.scss
- client/src/components/common/userInfo/userMenuItem/userMenuItem.module.scss
- client/src/components/menu/notificationSwitch/notificationSwitch.tsx
- client/src/components/menu/roomUserInfo/roomUserInfo.module.scss
- client/src/components/modals/timerSetting/timerSetting.tsx
- client/src/components/phaser/map/map.module.scss
- client/src/components/phaser/map/map.tsx
- client/src/components/phaser/map/phaserScene.ts
- client/src/components/timer/hooks/useTimer.tsx
- client/src/components/timer/timer.tsx
- client/src/constants/zoomLevel.const.ts
- client/src/jotai/atom.ts
- server/src/modules/rooms/dto/create-room.dto.ts
- server/src/modules/rooms/rooms.gateway.ts
QA에서 나왔던 내용들(player 관련 제외) 중 저의 몫 모두 수정하였습니다.
- 사용자 정보 메뉴 크기 수정 및 hover 상태 모양 변경
- 방에 접속한 사용자 정보창 커서 상태 변경, hover되는 크기 변경
: 마우스를 대면 커서가 poiner로 되어있어 default 상태로 바꿨습니다.(아직? 저기 클릭 못하기 때문)
: 사용자 정보 메뉴의 hover 디자인과 비슷하게 바꿨습니다.
- 맵에 radius 추가 (UI 거의 둥글어서)
- 맵 확대/축소 버튼 생성
(기본 상태)
(마우스 올리면)
- 타이머 설정할 때 99분인 경우 60초 이상일 때 발생하던 에러 해결
- 서비스 워커 위치 room으로 이동
- 방 이름에 띄어쓰기도 포함 가능하게 수정
> fix: QA 관련사항 수정

- build.sh
> fix: 클라이언트 액션 오류 수정

- build.sh
> release: 1.1.1 배포

- client/src/app/room/[roomId]/page.tsx
- conflict 해결하면서 import 중복으로 들어갔던 부분 수정
> fix: import 중복으로 들어간 부분 수정

- client/src/app/room/[roomId]/hooks/useScreenShare.ts
- client/src/components/phaser/map/phaserScene.ts
> fix: 린트 에러 수정

- client/src/app/room/[roomId]/page.tsx
> release: 1.1.3 배포

- client/src/components/common/userInfo/userInfo.module.scss
- server/src/common/guards/auth.guard.ts
- server/src/modules/auth/auth.service.ts
- server/src/modules/users/users.repository.ts
- 신규 가입 시 로그인 api에서 401에러가 뜨는 문제 수정
- 방이 없을 때 로비에서 유저 메뉴가 눌리지 않는 문제 수정
- 회원 가입 과정에서 db에 유저 정보를 저장한 후 그 정보를 가지고 토큰을 만들도록 수정 (id 있어야 해서)
- UserMenu에 z-index 추가
> fix: 신규 가입 시 로그인이 되지 않는 문제 수정

- client/src/apis/repository/notification.repository.ts
- client/src/apis/repository/room.repository.ts
- client/src/apis/repository/user.repository.ts
- client/src/apis/service/notification.service.ts
- client/src/apis/service/room.service.ts
- client/src/apis/service/user.service.ts
- client/src/modules/fetchClient.ts
- client/src/query/newQueryProvider.tsx
- server/src/app.module.ts
- server/src/common/interceptors/response.interceptor.ts
- server/src/common/interfaces/response.interface.ts
- server/src/modules/auth/auth.controller.ts
- server/src/modules/notification/notification.controller.ts
- server/src/modules/rooms/rooms.controller.ts
- api 응답 형태 통일
```
{
status: 200,
data: {...},
message: "..."
}
```
```
{
status: 500,
error: "...",
message: "..."
}
```
- 그에 따른 클라 측 api 코드 수정
- 에러 시 alert 뜨도록 수정
> fix: 성공, 실패 시의 api 응답 형식 통일

- client/src/apis/repository/notification.repository.ts
- client/src/apis/repository/room.repository.ts
- client/src/apis/repository/user.repository.ts
- client/src/apis/service/notification.service.ts
- client/src/apis/service/room.service.ts
- client/src/apis/service/user.service.ts
- client/src/modules/fetchClient.ts
- client/src/query/newQueryProvider.tsx
- server/src/app.module.ts
- server/src/common/interceptors/response.interceptor.ts
- server/src/common/interfaces/response.interface.ts
- server/src/modules/auth/auth.controller.ts
- server/src/modules/notification/notification.controller.ts
- server/src/modules/rooms/rooms.controller.ts
* fix: 응답 형식 통일 및 인터셉터 추가
* fix: 응답 형식 수정에 따른 repository, service 파일 수정
* fix: 리다이렉트 문제 및 메시지 수정
* fix: 에러 시 error 필드 추가
* fix: 서비스 덜 고쳐진 부분 수정
> release: 1.1.8 배포

- client/src/query/newQueryProvider.tsx
클라이언트의 `newQueryProvider.tsx` 파일에서 발생한 린트 에러 수정하였습니다
`newQueryProvider.tsx` 파일 프리티어 설정 적용
> style: 코드 포맷팅 수정 (린트 에러 해결)

- client/src/components/phaser/map/managers/configManager.ts
- client/src/components/phaser/map/managers/inputManager.ts
- client/src/components/phaser/map/managers/playerManager.ts
- client/src/components/phaser/map/managers/socketManager.ts
- client/src/components/phaser/map/map.tsx
- client/src/components/phaser/map/phaserScene.ts
- client/src/types/phaser.type.ts
* phaserScene 리팩토링
* phaser 관련 타입 분리
* config, input, player, socket 으로 manager 구분
> refactor: phaserScene 리팩토링

- server/src/common/guards/auth.guard.ts
- 게스트 로그인 jwt 토큰의 기간이 만료되어 게스트 로그인이 되지 않던 문제 수정
- 게스트 로그인 토큰의 경우 verify 검사하지 않도록 수정
> fix: 게스트 로그인 토큰 만료 문제 수정

- .github/workflows/server-deployment.yml
> release: 1.1.13 배포 

- server/src/modules/auth/auth.controller.ts
- server/src/modules/auth/auth.module.ts
- server/src/modules/auth/auth.service.ts
- server/src/modules/auth/strategies/jwt.strategy.ts
- configService -> process.env로 수정
- 환경변수 configService 로 불러오던 것이 서버 배포 후 에러가 나서 process.env로 수정
> fix: configService -> process.env로 수정

- client/src/components/phaser/map/map.tsx
- client/src/components/room/roomContent.tsx
임포트 오류 수정
`roomContent.tsx`, `map.tsx`에 임포트 잘못된 것들 수정했습니다.
> fix: 룸 페이지 임포트 오류 수정

- client/src/components/chat/chat.module.scss
> design: 채팅창의 방 제목 크기 조절, 말 줄임 추가
